name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - 'Release-*'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Get version from Git tags
        id: get_version
        run: |
          # Get the latest Release tag
          LATEST_TAG=$(git describe --tags --match "Release-*" --abbrev=0)
          if [ -z "$LATEST_TAG" ]; then
          echo "No Release tag found. Using default version."
          echo "VERSION=1.0.0" >> $GITHUB_OUTPUT
          exit 0
          fi
          echo "LATEST_TAG: $LATEST_TAG"
          # Extract version number from the tag (e.g., Release-1.0.1 -> 1.0.1)
          VERSION_NUMBER=$(echo "$LATEST_TAG" | sed 's/^Release-//')
          echo "VERSION_NUMBER: $VERSION_NUMBER"
          # Get the distance since the latest tag
          DISTANCE=$(git rev-list --count "$LATEST_TAG"..HEAD)
          echo "DISTANCE: $DISTANCE"
          # Append -SP<distance> if distance is greater than 0
          if [ "$DISTANCE" -gt 0 ]; then
            # Increment the third number
            VERSION_NUMBER=$(echo "$VERSION_NUMBER" | awk -F. -v OFS=. '{$3++; print}')
            # Add SP info
            DISTANCE=$(printf "%03d" "$DISTANCE")
            VERSION="$VERSION_NUMBER-SP$DISTANCE"
          else
            VERSION="$VERSION_NUMBER"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version: $VERSION"

      - name: Generate .env file in build directory
        run: |
          echo "UNIVERSAL_PAT=${{ secrets.UNIVERSAL_PAT }}" > ./dist/.env

      - name: Build project
        run: npm run build
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Start ASP.NET Core Service on Workspace
        run: |
          PAT=${{ secrets.UNIVERSAL_PAT }}
          CS_DISPLAY_NAME="CodeSpaceMain"
          OWNER="eduarddanziger"          # Replace with your GitHub username or organization name
          REPO="list-audio-react-app"                 # Replace with your repository name (if applicable)
          GITHUB_API_URL="https://api.github.com"
          # Headers for API requests
          HEADERS=(
              "-H" "Authorization: token $PAT"
              "-H" "Accept: application/vnd.github+json"
          )
          echo "Try getting codespaces..."
          INFO_URL="$GITHUB_API_URL/user/codespaces"
          RESPONSE=$(curl -s "${HEADERS[@]}" "$INFO_URL")
          # Check if the response contains Codespaces
          if echo "$RESPONSE" | jq -e '.codespaces == null or .codespaces == []' > /dev/null; then
              echo "No codespaces found."
              exit 1
          fi
          echo ".. Got codespaces. Try getting codespace name on display name..."
          CS_NAME=$(echo "$RESPONSE" | jq -r --arg NAME "$CS_DISPLAY_NAME" '.codespaces[] | select(.display_name == $NAME) | .name')
          echo ".. Got codespaces name: $CS_NAME. Try starting codespace..."
          START_URL="$GITHUB_API_URL/user/codespaces/$CS_NAME/start"
          curl -X POST "${HEADERS[@]}" "$START_URL"
          echo "...Codespace started"

      - name: Create Release
        run: |
          VERS=${{ steps.get_version.outputs.VERSION }}
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh release create "$VERS" --title "Audio Device Manager $VERS" --notes "Release of Audio Device Manager $VERS"
